In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_colwidth', 100)

In [2]:
df = pd.read_csv('sample_text.csv')
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel

In [4]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

embeddings = model.encode(
    df.text
)

print(embeddings.shape)

(8, 768)

In [10]:
dim = len(embeddings[0])

In [11]:
import faiss

index = faiss.IndexFlatL2(dim)
index

In [12]:
index.add(embeddings)

In [17]:
search_query = "I want to do my health checkup"

vec = model.encode(search_query)

In [18]:
vec.shape

(768,)

In [19]:
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [21]:
distances, I = index.search(svec, k=2)

In [22]:
I

array([[5, 0]], dtype=int64)

In [24]:
df.loc[I[0]]

                                                              text category
5  Navaratri dandiya program at Expo center in Mumbai this october    Event
0                    Meditation and yoga can improve mental health   Health